use std::error;

fn main() -> Result<(), Box<dyn error::Error>> {
    println!("--- Day 3: Spiral Memory ---");

    let input_data = 325489;

    Ok(())
}
